Repository CSCfi/beacon-network-ui, pull requests merged in 2019-10, with the labels that each got.

#6 UI changes
  package-lock.json
  public/index.html
  src/App.vue
  src/assets/elixir-white-orange-logo.png
  src/assets/eu-flag-bw.jpg
  src/components/BasicSearch.vue
  src/components/BeaconResults.vue
  src/components/BeaconResultsRow.vue
  src/components/ConnectedBeaconTile.vue
  src/components/ConnectedBeacons.vue
  src/components/Footer.vue
  src/components/HomeTabs.vue
  src/router.js
  src/views/Docs.vue
  src/views/DocsApi.vue
  src/views/Home.vue
  src/views/Join.vue
  src/views/Privacy.vue
  src/views/Tos.vue
Labels: enhancement

#14 Add Contributing guidelines as well as github templates and License
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#15 Small fixes for alignment
  src/components/BeaconResults.vue
  src/components/HomeTabs.vue
Labels: enhancement

#18 Run example query
  src/components/BasicSearch.vue
  src/components/HomeTabs.vue
Labels: enhancement

#17 Text pages format
  src/App.vue
  src/views/Docs.vue
  src/views/DocsApi.vue
  src/views/Privacy.vue
  src/views/Tos.vue
Labels: enhancement

#19 Detailed results
  src/components/BeaconResults.vue
  src/components/HomeTabs.vue
  src/views/Join.vue
Labels: enhancement

#20 Fix Logout
  .env
  src/App.vue
  src/views/Home.vue
Labels: bug

#22 Advanced search form
  src/components/AdvancedSearch.vue
  src/components/BasicSearch.vue
  src/components/BeaconResults.vue
  src/views/Home.vue
Labels: enhancement

#24 Fix the no results remplate
  src/components/BeaconResults.vue
Labels: bug
