Repository CSCfi/beacon-network-ui, pull requests merged in 2021-12, with the labels that each got.

#285 Release 1.4.0
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/BasicSearch.vue
  src/components/BasicSearchV2.vue
  src/components/BeaconResultTileDetails.vue
  src/components/BeaconResultTileDetailsV2.vue
  src/components/Footer.vue
  src/views/Guide.vue
  vue.config.js
Labels: Release

#287 small fixes and updates requested by customers
  src/components/BeaconResultTileDetails.vue
  src/components/BeaconResultTileDetailsV2.vue
  src/views/Home.vue
Labels: bug, enhancement

#288 prevent cookie toast duplicates #271
  src/views/Home.vue
Labels: bug

#289 Dev
  package-lock.json
  package.json
  src/components/BeaconResultTileDetails.vue
  src/components/BeaconResultTileDetailsV2.vue
  src/views/Home.vue
Labels: Release
