Repository CSCfi/beacon-network-ui, pull requests merged in 2022-05, with the labels that each got.

#324 Feature/search filter
  cypress/integration/SearchFiltering.test.ts
  src/components/BeaconResults.vue
  src/components/ListingV2.vue
Labels: enhancement

#421 Bugfix/page reload changes search
  cypress/integration/ListingsSearch.test.ts
  src/components/BeaconResults.vue
  src/components/ListingV2.vue
  src/views/Guide.vue
  src/views/Home.vue
Labels: bug

#422 Release v1.5.3
  cypress/integration/ListingsSearch.test.ts
  cypress/integration/SearchFiltering.test.ts
  package-lock.json
  package.json
  src/App.vue
  src/assets/elixir-login.png
  src/assets/login-ls.png
  src/components/BeaconResults.vue
  src/components/ListingV2.vue
  src/views/Guide.vue
  src/views/History.vue
  src/views/Home.vue
Labels: Release

#431 add multiple keyword for handling multiple results
  cypress/integration/BasicSearch.test.ts
Labels: bug
